import type { Service } from "@/types/service";

export const services: Service[] = [
  {
    slug: "transporte-aereo",
    title: "Transporte Aéreo",
    shortDescription: "Envíos express al mundo en 24–72 horas. Ideal para carga urgente, perecibles o de alto valor. Cobertura en 180+ países desde Ecuador. Cotiza tu envío hoy.",
    description: "Ofrecemos soluciones de carga aérea internacional para empresas y personas que necesitan velocidad y confiabilidad. Manejamos carga general, perecibles, productos farmacéuticos y mercancía de alto valor con los principales operadores aéreos del mundo.",
    icon: "Plane",
    image: "/images/services/transporte-aereo.jpg",
    features: [
      "Transporte puerta a puerta en 24–72 horas",
      "Tracking en tiempo real de tu envío",
      "Manejo de cargas peligrosas y especiales",
      "Seguro de carga incluido en cotización",
      "Consolidación de cargas para optimizar costos",
      "Cobertura en más de 180 países",
    ],
    process: [
      { step: 1, title: "Cotización", description: "Recibimos los detalles de tu carga y te enviamos una cotización personalizada en menos de 2 horas." },
      { step: 2, title: "Recolección", description: "Coordinamos la recolección en origen o recibimos la mercancía en nuestras bodegas." },
      { step: 3, title: "Despacho", description: "Gestionamos todos los documentos aduaneros y coordinamos con la aerolínea." },
      { step: 4, title: "Entrega", description: "Tu carga llega a destino con seguimiento completo en todo momento." },
    ],
    stats: [
      { value: "24–72h", label: "Tiempo de entrega" },
      { value: "180+", label: "Países destino" },
      { value: "99%", label: "Tasa de puntualidad" },
    ],
    cta: "Cotizar transporte aéreo",
  },
  {
    slug: "transporte-maritimo",
    title: "Transporte Marítimo",
    shortDescription: "La solución más económica para carga voluminosa. FCL (contenedor completo) y LCL (consolidado) a todos los puertos del mundo desde Ecuador. Cotiza tu flete hoy.",
    description: "Especialistas en carga marítima internacional. Ofrecemos contenedores completos (FCL) y consolidados (LCL) desde y hacia los principales puertos del mundo, con tarifas competitivas y seguimiento de tu contenedor en tiempo real.",
    icon: "Ship",
    image: "/images/services/transporte-maritimo.jpg",
    features: [
      "FCL (contenedor completo) y LCL (carga consolidada)",
      "Rutas directas a Asia, Europa y América",
      "Documentación de exportación e importación completa",
      "Seguimiento del buque en tiempo real",
      "Manejo de carga sobredimensionada",
      "Tarifas competitivas con acuerdos de volumen",
    ],
    process: [
      { step: 1, title: "Reserva de espacio", description: "Aseguramos espacio en el buque y te enviamos la confirmación de booking." },
      { step: 2, title: "Instrucciones de embarque", description: "Preparamos toda la documentación: BL, packing list, factura comercial." },
      { step: 3, title: "Zarpe y tránsito", description: "Monitoreamos el buque durante toda la travesía y te informamos de cualquier novedad." },
      { step: 4, title: "Arribo y entrega", description: "Gestionamos el desaduanaje a la llegada y coordinamos la entrega final." },
    ],
    stats: [
      { value: "15–45d", label: "Tiempo de tránsito" },
      { value: "FCL/LCL", label: "Opciones de carga" },
      { value: "50+", label: "Puertos conectados" },
    ],
    cta: "Cotizar flete marítimo",
  },
  {
    slug: "transporte-terrestre-internacional",
    title: "Transporte Terrestre Internacional",
    shortDescription: "Conexión terrestre con Colombia, Perú y Chile. Ideal para cargas frecuentes en la región. Flota propia con GPS y gestión aduanera en cada frontera. Cotiza.",
    description: "Servicio de transporte por carretera hacia y desde los principales países fronterizos: Colombia, Perú y Chile. Contamos con flota propia y alianzas con los mejores transportistas de la región para garantizar entregas puntuales.",
    icon: "Truck",
    image: "/images/services/transporte-terrestre.jpg",
    features: [
      "Cobertura a Colombia, Perú y Chile",
      "Flota moderna con GPS y temperatura controlada",
      "Manejo de documentos aduaneros fronterizos",
      "Servicio de grupaje (LTL) disponible",
      "Entregas programadas o express",
      "Seguimiento en tiempo real",
    ],
    process: [
      { step: 1, title: "Planificación de ruta", description: "Definimos la ruta óptima según peso, volumen y urgencia de tu carga." },
      { step: 2, title: "Carga y despacho", description: "Inspeccionamos y precintamos la carga. Preparamos documentos fronterizos." },
      { step: 3, title: "Cruce fronterizo", description: "Gestionamos el paso aduanero con nuestros agentes en cada frontera." },
      { step: 4, title: "Entrega en destino", description: "Entregamos puerta a puerta con confirmación de recepción." },
    ],
    cta: "Cotizar transporte terrestre",
  },
  {
    slug: "courier-internacional",
    title: "Courier Internacional",
    shortDescription: "Envíos de paquetes y documentos a 220+ países. Rápido, económico y con tracking en tiempo real. Alianzas con FedEx, DHL, UPS y TNT. Cotiza tu envío.",
    description: "Servicio de mensajería internacional para paquetes de hasta 30 kg. Ideal para muestras comerciales, documentos y pedidos de e-commerce. Alianzas con los principales operadores globales: FedEx, DHL, UPS y TNT.",
    icon: "Package",
    image: "/images/services/courier-internacional.jpg",
    features: [
      "Entrega en 2–7 días hábiles según destino",
      "Cobertura en 220+ países y territorios",
      "Tracking en tiempo real con notificaciones",
      "Servicio de consolidación para reducir costos",
      "Manejo de envíos de e-commerce",
      "Atención personalizada 24/7",
    ],
    process: [
      { step: 1, title: "Recepción", description: "Recibimos tu paquete en nuestra oficina o coordinamos la recolección a domicilio." },
      { step: 2, title: "Clasificación", description: "Pesamos, medimos y verificamos el contenido para elegir el operador óptimo." },
      { step: 3, title: "Despacho", description: "Enviamos con el operador y te entregamos el número de guía para rastreo." },
      { step: 4, title: "Confirmación", description: "Recibes notificación cuando tu paquete es entregado en destino." },
    ],
    cta: "Cotizar envío courier",
  },
  {
    slug: "agenciamiento-aduanero",
    title: "Agenciamiento Aduanero",
    shortDescription: "Agentes certificados por la SENAE. Trámites de importación y exportación sin complicaciones. Evitamos multas y optimizamos tus tributos dentro del marco legal. Consúltanos.",
    description: "Somos agentes de aduana certificados por la SENAE. Gestionamos el despacho de importaciones y exportaciones con precisión y rapidez. Clasificamos correctamente tu mercancía, evitamos multas y optimizamos los tributos dentro del marco legal.",
    icon: "BriefcaseBusiness",
    image: "/images/services/agenciamiento-aduanero.jpg",
    features: [
      "Aforo electrónico y físico de mercancías",
      "Clasificación arancelaria precisa",
      "Gestión de permisos y certificados especiales",
      "Asesoría en regímenes aduaneros especiales",
      "Liquidación de tributos optimizada",
      "Atención a observaciones del aforo en 24h",
    ],
    process: [
      { step: 1, title: "Recepción de documentos", description: "Nos envías factura, BL/AWB, packing list y demás documentos de importación." },
      { step: 2, title: "Clasificación", description: "Determinamos la partida arancelaria correcta y calculamos los tributos." },
      { step: 3, title: "Declaración", description: "Ingresamos la declaración aduanera en el sistema ECUAPASS de la SENAE." },
      { step: 4, title: "Levante", description: "Gestionamos el levante y coordinamos el retiro de tu mercancía del depósito." },
    ],
    cta: "Consultar agenciamiento",
  },
  {
    slug: "transporte-nacional",
    title: "Transporte Nacional",
    shortDescription: "Distribución en las 24 provincias del Ecuador. Flota rastreada, confirmación de entrega y cobertura hasta el último kilómetro. Ideal para importadores. Cotiza.",
    description: "Red de distribución terrestre que cubre las 24 provincias del Ecuador. Desde Quito, Guayaquil y Cuenca conectamos con todas las ciudades del país. Ideal para empresas importadoras que necesitan distribuir su mercancía desaduanizada.",
    icon: "MapPin",
    image: "/images/services/transporte-nacional.jpg",
    features: [
      "Cobertura en las 24 provincias",
      "Servicio de última milla a domicilio",
      "Flota de camiones de 1 a 30 toneladas",
      "Manejo de carga frágil y especial",
      "Consolidación de cargas para optimizar costos",
      "Entrega con confirmación de recepción",
    ],
    process: [
      { step: 1, title: "Solicitud", description: "Nos indicas el origen, destino, peso y tipo de carga para cotizarte." },
      { step: 2, title: "Recolección", description: "Pasamos a recoger tu carga en el punto acordado dentro de Guayaquil o Quito." },
      { step: 3, title: "Traslado", description: "Tu carga viaja en nuestra flota rastreada hasta el destino." },
      { step: 4, title: "Entrega", description: "Entregamos con firma de recepción y evidencia fotográfica." },
    ],
    cta: "Cotizar envío nacional",
  },
  {
    slug: "seguros-custodia-armada",
    title: "Seguros y Custodia Armada",
    shortDescription: "Seguros all-risk y custodia armada para carga de alto valor. Protección integral para electrónica, joyería y mercancía sensible en Ecuador. Evaluación de riesgo sin costo.",
    description: "Protección integral para mercancías de alto valor. Ofrecemos seguros de carga all-risk para importaciones y exportaciones, más servicio de custodia armada para traslados de mercancía sensible dentro del Ecuador.",
    icon: "ShieldCheck",
    image: "/images/services/seguros-custodia.jpg",
    features: [
      "Seguro all-risk para toda la cadena logística",
      "Custodia armada para traslados sensibles",
      "Cobertura para electrónica, joyería y arte",
      "Proceso de reclamación ágil y acompañado",
      "Alianzas con las principales aseguradoras",
      "Evaluación de riesgo sin costo",
    ],
    process: [
      { step: 1, title: "Evaluación", description: "Analizamos el tipo de carga, ruta y valor para diseñar la cobertura adecuada." },
      { step: 2, title: "Cotización", description: "Te presentamos opciones de seguro con distintos niveles de cobertura y costo." },
      { step: 3, title: "Emisión de póliza", description: "Emitimos la póliza antes del despacho de tu mercancía." },
      { step: 4, title: "Acompañamiento", description: "En caso de siniestro, te acompañamos durante todo el proceso de reclamación." },
    ],
    cta: "Asegurar mi carga",
  },
  {
    slug: "almacenamiento-distribucion",
    title: "Almacenamiento y Distribución",
    shortDescription: "Bodegas seguras en Guayaquil y Quito con sistema WMS en línea. Almacena, gestiona y distribuye tu mercancía importada desde un solo lugar. Consulta disponibilidad.",
    description: "Espacios de almacenamiento seguro en Guayaquil y Quito para tu mercancía importada. Sistema de gestión de inventario (WMS) en línea, servicio de picking & packing y distribución a nivel nacional desde nuestras bodegas.",
    icon: "Warehouse",
    image: "/images/services/almacenamiento.jpg",
    features: [
      "Bodegas en Guayaquil y Quito",
      "Sistema WMS con acceso en línea 24/7",
      "Servicio de picking, packing y etiquetado",
      "Almacenamiento en temperatura controlada",
      "Distribución last-mile integrada",
      "Inventario en tiempo real con alertas",
    ],
    process: [
      { step: 1, title: "Recepción", description: "Recibimos tu mercancía, la inspeccionamos y registramos en el sistema WMS." },
      { step: 2, title: "Almacenamiento", description: "Asignamos ubicación óptima según tipo de producto y rotación." },
      { step: 3, title: "Gestión de pedidos", description: "Procesamos tus órdenes de despacho en menos de 4 horas hábiles." },
      { step: 4, title: "Distribución", description: "Despachamos a tus clientes finales o puntos de venta en todo el Ecuador." },
    ],
    cta: "Consultar almacenamiento",
  },
  {
    slug: "busqueda-proveedores",
    title: "Búsqueda de Proveedores",
    shortDescription: "Encontramos el proveedor ideal en China, EE.UU. o Europa para tu producto. Evaluamos fábricas, negociamos precios y gestionamos el control de calidad antes del embarque.",
    description: "Servicio de sourcing internacional para empresas que desean importar pero no tienen contactos en origen. Nuestro equipo con presencia en Asia y aliados en EE.UU. y Europa identifica, evalúa y negocia con proveedores para que tú solo te preocupes de vender.",
    icon: "Search",
    image: "/images/services/busqueda-proveedores.jpg",
    features: [
      "Investigación de mercado en origen",
      "Evaluación y visita a fábricas en China",
      "Negociación de precios y condiciones",
      "Control de calidad antes del embarque",
      "Gestión de muestras y prototipos",
      "Asesoría en incoterms y términos de pago",
    ],
    process: [
      { step: 1, title: "Briefing", description: "Nos describes el producto que necesitas: especificaciones, cantidad y presupuesto." },
      { step: 2, title: "Investigación", description: "Identificamos 3–5 proveedores calificados y verificamos su historial." },
      { step: 3, title: "Presentación", description: "Te presentamos las opciones con cotizaciones comparativas y nuestra recomendación." },
      { step: 4, title: "Coordinación", description: "Una vez elegido el proveedor, coordinamos la producción, QC y el embarque." },
    ],
    cta: "Buscar proveedor",
  },
];

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((s) => s.slug === slug);
}
